// <auto-generated />
namespace Fantasy.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.1-21010")]
    public sealed partial class TeamDivisionKey : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(TeamDivisionKey));
        
        string IMigrationMetadata.Id
        {
            get { return "201311120436258_TeamDivisionKey"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
